language: csharp
solution: Stupify.sln
mono: none
dotnet: 2.1.4
install:
- dotnet restore
script:
- dotnet build
- dotnet test tests/TicTacZapTests/TicTacZapTests.csproj
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true