language: csharp
solution: Stupify.sln
mono: none
dotnet: 2.1.4
install:
- dotnet restore -s https://api.nuget.org/v3/index.json -s https://www.myget.org/F/discord-net/api/v3/index.json -s https://www.myget.org/F/rogueexception/api/v3/index.json
script:
- dotnet build
- dotnet test tests/TicTacZapTests/TicTacZapTests.csproj
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true